[package]
name = "instrumentation"
version.workspace = true
edition.workspace = true

[[bin]]
name = "instrumentation"
path = "src/main.rs"


[dependencies]
wasmparser = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
ic-wasm-transform = { workspace = true }