[package]
name = "canister_fuzzer"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
ic-state-machine-tests = { workspace = true }
ic-types = { workspace = true }
ic-canister-sandbox-backend-lib = { workspace =  true }

candid = { workspace = true }
slog = { workspace = true }
libafl = { workspace = true }
libafl_bolts = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
wirm = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }