name: CI

on:
  workflow_call:
  pull_request:
    branches: [ "main" ] 

env:
  RUST_VERSION: 1.89.0
  DFX_VERSION: 0.29.1
  MOPS_VERSION: 1

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: "${{ env.RUST_VERSION }}"
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Setup DFX
        uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365
        with:
          dfx-version: "${{ env.DFX_VERSION }}"

      - name: Setup MOPS
        uses: dfinity/setup-mops@3e94e453352269b34137b5ce49f09a8df81bed7d # v1.4.1
        with:
          mops-version: "${{ env.MOPS_VERSION }}"

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Run Tests
        run: cargo test -- --color always
        env:
          RUST_BACKTRACE: 1

      - name: Test examples
        run: |
          ./scripts/test_run.sh